### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Mikefizzy** [34j/so-vits-svc-fork#195] opened 2023-03-31 09:58 UTC
Often songs have continuous singing making the chunks to process quite large.
with 6 gigs of vram, it often crashes when trying to process. 

To circumvent, I often have to open premiere pro and split the song into chunks.
which is annoying.

Would it be possible to fix this within the program? perhaps some kind of low memory mode?

**Comment by milkmanjr** [comment] 2023-03-31 11:57
You can split the song into 10 second chunks automatically using ffmpeg

**Comment by 34j** [comment] 2023-03-31 13:51
Try decreasing db_thresh (increase absolute value)

**Comment by 34j** [comment] 2023-04-01 10:20
Duplicate of #183

**Closed by 34j** 2023-04-01 10:20 UTC
Labels: bug
