### ISSUE TITLE
Using all RAM at once, then erroring

### ISSUE THREAD

**Issue by Lordmau5** [34j/so-vits-svc-fork#136] opened 2023-03-26 12:50 UTC
**Describe the bug**
When running `svc pre-resample` with the newest version (1.4.2) it now uses up all my RAM and then errors out with the following error
![image](https://user-images.githubusercontent.com/1345036/227776767-1db19f58-084b-4ab6-a049-553d9c5eca73.png)

```
E:\Development\so-vits-svc-4.0\Robbie Rotten>svc pre-resample
[14:47:25] INFO     [14:47:25] Version: 1.4.2                                                             __main__.py:20Preprocessing: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:30<00:00,  1.19it/s]
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\externals\loky\process_executor.py", line 428, in _process_worker
    r = call_item()
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\externals\loky\process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\so_vits_svc_fork\preprocess_resample.py", line 63, in _preprocess_one
    audio, _ = librosa.effects.trim(audio, top_db=20)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\librosa\effects.py", line 495, in trim
    non_silent = _signal_to_frame_nonsilent(
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\librosa\effects.py", line 440, in _signal_to_frame_nonsilent
    mse = feature.rms(y=y, frame_length=frame_length, hop_length=hop_length)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\librosa\feature\spectral.py", line 955, in rms
    power = np.mean(np.abs(x) ** 2, axis=-2, keepdims=True)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.32 GiB for an array with shape (304586, 2048, 1) and data type float32
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\Scripts\svc.exe\__main__.py", line 7, in <module>
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\so_vits_svc_fork\__main__.py", line 420, in pre_resample
    preprocess_resample(
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\so_vits_svc_fork\preprocess_resample.py", line 111, in preprocess_resample
    Parallel(n_jobs=n_jobs)(
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Dustin\AppData\Roaming\Python\Python310\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.32 GiB for an array with shape (304586, 2048, 1) and data type float32
```

**To Reproduce**
Run `svc pre-resample` with a bunch of files in a sub-folder of `dataset/`

**Additional context**
Rolled back to 1.4.1 and it works perfectly fine on those same clips, only used a bit of my RAM
![image](https://user-images.githubusercontent.com/1345036/227776844-c7939271-3818-446d-bb00-643eb0578c89.png)

**Comment by Satisfy256** [comment] 2023-03-26 12:58
maybe because dtype="float32" was added, so maybe it should be "int16" for less memory usage.

**Comment by Lordmau5** [comment] 2023-03-26 13:01
> maybe because in version 1.4.2 dtype="float32" was added, so maybe it should be "int16" for less memory usage.

Is float32 really that much worse for the performance compared to int16?
I am having a hard time believing that (though I don't know the in-depth details of different audio formats)
Maybe there's some extra configuration needed for the `soundfile` library?

**Comment by Satisfy256** [comment] 2023-03-26 13:14
> > maybe because in version 1.4.2 dtype="float32" was added, so maybe it should be "int16" for less memory usage.
> 
> Is float32 really that much worse for the performance compared to int16? I am having a hard time believing that (though I don't know the in-depth details of different audio formats) Maybe there's some extra configuration needed for the `soundfile` library?

Yes it's not that, my bad. Try running: svc pre-resample -n 1

**Comment by 34j** [comment] 2023-03-26 13:14
It took me terribly long to understand how to use soundfile and librosa. Should be fixed in the new release.

**Comment by Lordmau5** [comment] 2023-03-26 13:22
It's still hitting the RAM limit on my PC.

As per @Satisfy256 's suggestion, I manually specified `-n` to be 8 and that only used like half of my RAM in total (still a lot but hey)

I see that by default it's using `-1` which I assume is either gonna be "maximum" or "auto-detect"... Optimally auto-detect would be best and, if it's already that way, then it seems like it's not detecting it properly

**Comment by 34j** [comment] 2023-03-26 13:44
My brain destroyed

**Comment by Lordmau5** [comment] 2023-03-26 13:50
> My brain was destroyed

Yeah I kinda explained like 3 different things there

___
Okay: So running `svc pre-resample` without specifying the number of jobs will cause it to use all my CPU cores / threads.
This in turn means it will also use a lot of RAM because it tries to hold all (in my case) 32 files in memory at once.

Doing `-n 8` means I'll limit it to 8 threads and that means it won't use ALL my RAM, and also not all my cores.

However, running 8 threads at the same time is **slower** than just doing `-n 1` like you had it before adding the launch flag.

___
Now, when I do the setup with `svc pre-resample -n 8` or, from what I can tell, **anything but 1 parallel job**, and later on do `svc pre-hubert` to prepare the files for training

I will not be able to use these files in training.

It will throw the error I mentioned up there.

**Comment by 34j** [comment] 2023-03-26 14:32
Actually, Hubert/f0 is not recalculated. I have changed my algorithm, is the third one really correct?

**Comment by 34j** [comment] 2023-03-26 14:33
As for the second one, I am in almost the same environment as you, but I cannot reproduce it.

**Comment by 34j** [comment] 2023-03-26 14:34
The first has already been resolved.

**Comment by Lordmau5** [comment] 2023-03-26 14:41
> Actually, Hubert/f0 is not recalculated. I have changed my algorithm, is the third one really correct?

I tried running my setup script for it again just now (pre-resample, pre-config and pre-hubert), and I even removed the `-n 1` part of `pre-resample`, and it worked just fine now... weird, I shall blame this on something else.

In that case, the 2nd one is also resolved, so yeah. This is weird. I have no idea what caused this but I will try to observe it a bit more and report back if I find it again

**Closed** 2023-03-26 14:47 UTC
Labels: bug
