### ISSUE TITLE
Failed to build fairseq

### ISSUE THREAD

**Issue by yifenglv46** [34j/so-vits-svc-fork#325] opened 2023-04-14 09:38 UTC
copying fairseq\config\model\wav2vec2\wav2vec2_large.yaml -> build\lib.win-amd64-cpython-310\fairseq\config\model\wav2vec2
      running build_ext
      cythoning fairseq/data/data_utils_fast.pyx to fairseq/data\data_utils_fast.cpp
      cythoning fairseq/data/token_block_utils_fast.pyx to fairseq/data\token_block_utils_fast.cpp
      building 'fairseq.libbleu' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\fairseq
      creating build\temp.win-amd64-cpython-310\Release\fairseq\clib
      creating build\temp.win-amd64-cpython-310\Release\fairseq\clib\libbleu
      "d:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IL:\so-vits-svc\venv\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\Include "-Id:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-Id:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /Fobuild\temp.win-amd64-cpython-310\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
      cl: 命令行 warning D9002 :忽略未知??“-std=c++11”
      cl: 命令行 warning D9002 :忽略未知??“-O3”
      libbleu.cpp
      d:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: ?法打?包括文件: “crtdbg.h”: No such file or directory
      error: command 'd:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by 34j** [comment] 2023-04-14 10:15
Duplicate of #142

**Closed** 2023-04-14 10:16 UTC
Labels: bug

**Comment by yifenglv46** [comment] 2023-04-14 10:27
it works,thanks ^_^
